import PDFDocument from 'pdfkit';

interface ScanData {
  id: string;
  targetName: string;
  scanDate: string;
  duration: number;
  totalFiles: number;
  phpFiles: number;
  totalFindings: number;
  bySeverity: Record<string, number>;
  byCategory: Record<string, number>;
  results: Array<{
    checkId: string;
    checkName: string;
    category: string;
    severity: string;
    description: string;
    findings: Array<{
      file: string;
      line: number;
      message: string;
      code: string;
      details: string;
    }>;
  }>;
}

const sevColors: Record<string, string> = {
  critical: '#dc2626',
  high: '#ea580c',
  medium: '#ca8a04',
  low: '#0891b2',
  info: '#6b7280',
};

export function generatePdfReport(scan: ScanData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ size: 'A4', margin: 40 });
      const chunks: Buffer[] = [];

      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Title
      doc.fontSize(20).fillColor('#1e40af').text('WP-SENTINEL Security Report', { align: 'center' });
      doc.moveDown(0.3);
      doc.fontSize(11).fillColor('#374151').text(`Target: ${scan.targetName}`, { align: 'center' });
      doc.fontSize(9).fillColor('#6b7280').text(
        `Date: ${new Date(scan.scanDate).toLocaleString()} | Duration: ${scan.duration}ms | Files: ${scan.totalFiles} (${scan.phpFiles} PHP)`,
        { align: 'center' }
      );
      doc.moveDown(1);

      // Severity summary
      doc.fontSize(13).fillColor('#1e293b').text('Severity Summary');
      doc.moveDown(0.3);
      const sevHeader = ['Severity', 'Count', 'Percentage'];
      const sevRows = ['critical', 'high', 'medium', 'low', 'info'].map(sev => [
        sev.toUpperCase(),
        String(scan.bySeverity[sev] || 0),
        scan.totalFindings > 0 ? `${((scan.bySeverity[sev] || 0) / scan.totalFindings * 100).toFixed(1)}%` : '0%',
      ]);

      drawTable(doc, sevHeader, sevRows, [150, 100, 100]);
      doc.moveDown(1);

      // Category breakdown
      doc.fontSize(13).fillColor('#1e293b').text('Category Breakdown');
      doc.moveDown(0.3);
      const catHeader = ['Category', 'Findings'];
      const catRows = Object.entries(scan.byCategory)
        .filter(([, v]) => v > 0)
        .sort((a, b) => b[1] - a[1])
        .map(([cat, count]) => [cat, String(count)]);

      if (catRows.length > 0) {
        drawTable(doc, catHeader, catRows, [200, 100]);
        doc.moveDown(1);
      }

      // Detailed findings
      const findingsWithItems = scan.results.filter(r => r.findings.length > 0);
      if (findingsWithItems.length > 0) {
        doc.fontSize(13).fillColor('#1e293b').text('Detailed Findings');
        doc.moveDown(0.3);

        for (const result of findingsWithItems) {
          if (doc.y > 700) doc.addPage();

          const color = sevColors[result.severity] || '#000000';
          doc.fontSize(11).fillColor(color).text(`[${result.severity.toUpperCase()}] ${result.checkId}: ${result.checkName}`);
          doc.fontSize(8).fillColor('#6b7280').text(result.description);
          doc.moveDown(0.3);

          const findingHeader = ['File', 'Line', 'Message'];
          const findingRows = result.findings.slice(0, 30).map(f => [
            f.file.length > 40 ? '...' + f.file.slice(-37) : f.file,
            String(f.line),
            f.message.length > 60 ? f.message.slice(0, 57) + '...' : f.message,
          ]);

          drawTable(doc, findingHeader, findingRows, [180, 40, 230]);
          doc.moveDown(0.5);
        }
      }

      // Footer
      doc.fontSize(7).fillColor('#9ca3af').text(
        `Generated by WP-SENTINEL Security Analyzer | ${new Date().toLocaleString()}`,
        40, doc.page.height - 50, { align: 'center' }
      );

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}

function drawTable(doc: PDFKit.PDFDocument, headers: string[], rows: string[][], widths: number[]) {
  const startX = 40;
  let y = doc.y;

  // Header
  doc.fontSize(9).fillColor('#ffffff');
  let x = startX;
  for (let i = 0; i < headers.length; i++) {
    doc.rect(x, y, widths[i], 18).fill('#1e40af');
    doc.fillColor('#ffffff').text(headers[i], x + 4, y + 4, { width: widths[i] - 8 });
    x += widths[i];
  }
  y += 18;

  // Rows
  for (const row of rows) {
    if (y > 750) {
      doc.addPage();
      y = 40;
    }
    x = startX;
    for (let i = 0; i < row.length; i++) {
      doc.rect(x, y, widths[i], 16).fill('#f8fafc').stroke('#e2e8f0');
      doc.fontSize(8).fillColor('#1e293b').text(row[i], x + 4, y + 3, { width: widths[i] - 8 });
      x += widths[i];
    }
    y += 16;
  }

  doc.y = y + 4;
}
